before_script:
  - mvn clean

production:
  script:
    - mvn -U package -Dsettings.security=/home/ci/settings.xml
    - java -cp /home/ci/allatori/allatori.jar com.allatori.Obfuscate ./target/classes/config.xml
  type: deploy
  only:
    - master
